# valhalla-secrets.fish — loads secrets generated by `valhalla secret inject`.
#
# This file IS safe to commit (it contains no secrets). It simply sources the
# generated plaintext file, which lives outside the repo at
# ~/.local/share/valhalla/secrets.fish by default.
#
# To update secrets:
#   valhalla secret add <path>     # add/update a value
#   valhalla secret inject         # regenerate the file below

set -l _valhalla_secrets "$HOME/.local/share/valhalla/secrets.fish"

if test -f "$_valhalla_secrets"
    source "$_valhalla_secrets"
else
    echo "valhalla: $_valhalla_secrets not found." >&2
    echo "         run `valhalla secret inject` to generate it." >&2
end

set -e _valhalla_secrets
