// Package cmd — `valhalla completion install` subcommand.
//
// Cobra auto-generates a `completion` command with bash/zsh/fish/powershell
// subcommands. We add `install` on top to make fish setup zero-config:
//
//	valhalla completion install
//
// writes the fish completion script to the right location, following the
// valhalla fish symlink if present so completions sync across machines.
package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var completionInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install fish completion to ~/.config/fish/completions/",
	Long: `install writes the valhalla fish completion script so it's auto-loaded.

If ~/.config/fish is a symlink into your valhalla repo (the standard setup
after 'valhalla apply'), the completion file is written there and tracked
in git — so every machine that pulls gets the same completions.

Otherwise, the script goes to ~/.config/fish/completions/valhalla.fish.

After install, restart fish (or 'exec fish') to enable:
  valhalla secret get <TAB>      → lists stored secrets
  valhalla secret rm <TAB>       → lists stored secrets
  valhalla devices remove <TAB>  → lists device names
  valhalla secret inject --shell <TAB> → fish|posix|env|json`,
	Args: cobra.NoArgs,
	RunE: runCompletionInstall,
}

func init() {
	// Cobra lazily creates the completion command. Force it to exist
	// by accessing the command, then attach our subcommand.
	completionCmd := rootCmd.CompletionOptions
	_ = completionCmd
	// Trigger creation of the default completion command by calling
	// InitDefaultCompletionCmd explicitly.
	rootCmd.InitDefaultCompletionCmd()
	// Now find it and attach `install`.
	for _, c := range rootCmd.Commands() {
		if c.Name() == "completion" {
			c.AddCommand(completionInstallCmd)
			return
		}
	}
}

func runCompletionInstall(_ *cobra.Command, _ []string) error {
	// Generate fish completion script via cobra (writes to a buffer).
	var buf bytes.Buffer
	if err := rootCmd.GenFishCompletion(&buf, true); err != nil {
		return fmt.Errorf("generate: %w", err)
	}
	// Prepend a header so people know not to hand-edit.
	header := "# Generated by `valhalla completion install` — DO NOT EDIT.\n# Re-run that command to refresh.\n\n"
	content := header + buf.String()

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	// Detect valhalla-managed fish dir (symlinked from ~/.config/fish).
	targetDir := filepath.Join(home, ".config", "fish", "completions")
	if fishLink, err := os.Readlink(filepath.Join(home, ".config", "fish")); err == nil {
		// Resolve and use its completions/ subdir.
		targetDir = filepath.Join(fishLink, "completions")
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	target := filepath.Join(targetDir, "valhalla.fish")
	if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Printf("✓ installed fish completion → %s\n", target)
	fmt.Println()
	fmt.Println("Restart fish (or 'exec fish') to activate. Try:")
	fmt.Println("  valhalla secret get <TAB>")
	return nil
}
