package secretcmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/FadingRose/valhalla/internal/manifest"
	"github.com/FadingRose/valhalla/internal/secretage"
	"github.com/spf13/cobra"
)

var (
	injectShell   string
	injectOutput  string
	injectDryRun  bool
	injectProfile string
)

// shellTemplates maps a shell name to its line template.
// The template receives .Var (variable name) and .Value (decrypted secret).
var shellTemplates = map[string]string{
	"fish":   "set -gx {{.Var}} {{.Value | quote}}",
	"posix":  "export {{.Var}}={{.Value | quote}}",
	"env":    "{{.Var}}={{.Value}}",
	"json":   `  "{{.Var}}": "{{.Value}}"`,
}

// fileHeaders are the warning banners prepended to generated files.
var fileHeaders = map[string]string{
	"fish": `# ⚠️  GENERATED BY valhalla — DO NOT EDIT
# This file is regenerated on every ` + "`valhalla secret inject`" + `.
# To change a value, use:
#     valhalla secret add <path>
# Then re-run:
#     valhalla secret inject

`,
	"posix": `# ⚠️  GENERATED BY valhalla — DO NOT EDIT
# Source this file from your shell rc:
#     [ -f "$HOME/.config/shell/secrets.sh" ] && . "$HOME/.config/shell/secrets.sh"

`,
	"env": `# GENERATED BY valhalla — DO NOT EDIT
# Load with: set -a && . .env && set +a

`,
	"json": `{
`,
}

var secretInjectCmd = &cobra.Command{
	Use:   "inject",
	Short: "Decrypt secrets and write them to a shell env file",
	Long: `inject reads [secrets] from manifest.toml, decrypts every entry, and
writes the result to the configured output file in the requested shell format.

The output file gets a warning header and is written with mode 0600.
A temporary file is used during write, then renamed atomically.

Supported shells: fish (default), posix, env, json.`,
	Args: cobra.NoArgs,
	RunE: runInject,
}

func init() {
	secretInjectCmd.Flags().StringVar(&injectShell, "shell", "",
		"output format: fish|posix|env|json (default: from manifest or fish)")
	secretInjectCmd.Flags().StringVar(&injectOutput, "output", "",
		"override output file path (default: from manifest)")
	secretInjectCmd.Flags().BoolVar(&injectDryRun, "dry-run", false,
		"print to stdout instead of writing file")
	secretCmd.AddCommand(secretInjectCmd)
}

func runInject(_ *cobra.Command, _ []string) error {
	repo, err := resolveRepo()
	if err != nil {
		return err
	}
	m, err := manifest.Load(repo)
	if err != nil {
		return err
	}

	// Resolve shell (flag > manifest > default fish).
	shell := injectShell
	if shell == "" {
		shell = "fish"
	}
	if _, ok := shellTemplates[shell]; !ok {
		return fmt.Errorf("unsupported shell %q (use fish|posix|env|json)", shell)
	}

	// Resolve output path (flag > manifest).
	outPath := injectOutput
	if outPath == "" {
		outPath = m.Secrets.Output
	}
	if outPath == "" && !injectDryRun {
		return fmt.Errorf("no output path: set [secrets].output in manifest.toml or use --output")
	}

	// Gather entries (base + profile extras if profile matched).
	profile := m.SelectProfile(injectProfile)
	entries := m.AllEntries(profile)
	if len(entries) == 0 {
		return fmt.Errorf("no [[secrets.inject]] entries in manifest.toml")
	}

	secretsDir := resolveStoreDir(repo)
	identPath := defaultIdentityPath()
	if _, err := os.Stat(identPath); err != nil {
		return fmt.Errorf("identity missing at %s: %w", identPath, err)
	}

	// Decrypt all entries.
	var pairs []kvPair
	failed := 0
	for _, e := range entries {
		val, err := secretage.DecryptFromFile(secretsDir, e.Path, identPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  ✗ %s (%s): %v\n", e.Var, e.Path, err)
			failed++
			continue
		}
		pairs = append(pairs, kvPair{Var: e.Var, Value: string(val)})
	}
	if failed > 0 {
		return fmt.Errorf("%d/%d secrets failed to decrypt", failed, len(entries))
	}

	// Render output.
	content, err := renderShell(shell, pairs)
	if err != nil {
		return err
	}

	if injectDryRun {
		fmt.Print(content)
		return nil
	}

	// Expand ~ in output path.
	expanded, err := manifest.ExpandTarget(outPath)
	if err != nil {
		return err
	}

	if err := writeAtomic(expanded, content, 0o600); err != nil {
		return err
	}

	fmt.Printf("✓ injected %d secrets → %s (%s, mode 0600)\n",
		len(pairs), expanded, shell)
	return nil
}

// kvPair is the rendered key/value pair passed to the shell template.
type kvPair struct {
	Var   string
	Value string
}

// renderShell produces the file body using the shell template.
func renderShell(shell string, pairs []kvPair) (string, error) {
	tplText := shellTemplates[shell]
	tpl, err := template.New("line").Funcs(template.FuncMap{
		"quote": shellQuote,
	}).Parse(tplText)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	buf.WriteString(fileHeaders[shell])

	// JSON needs array-style wrapping.
	if shell == "json" {
		for i, p := range pairs {
			if err := tpl.Execute(&buf, p); err != nil {
				return "", err
			}
			if i < len(pairs)-1 {
				buf.WriteString(",")
			}
			buf.WriteString("\n")
		}
		buf.WriteString("}\n")
		return buf.String(), nil
	}

	for _, p := range pairs {
		if err := tpl.Execute(&buf, p); err != nil {
			return "", err
		}
		buf.WriteString("\n")
	}
	return buf.String(), nil
}

// shellQuote wraps a value in double quotes if it contains special chars.
// Simple policy: always quote unless the value is purely [A-Za-z0-9_./:-].
func shellQuote(s string) string {
	if s == "" {
		return `""`
	}
	safe := true
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z',
			r >= 'a' && r <= 'z',
			r >= '0' && r <= '9',
			r == '_', r == '.', r == '/', r == ':', r == '-':
		default:
			safe = false
		}
	}
	if safe {
		return s
	}
	// Escape any embedded double-quotes.
	escaped := strings.ReplaceAll(s, `"`, `\"`)
	return `"` + escaped + `"`
}

// writeAtomic writes data to a temp file in the same dir, then renames.
// Ensures readers never see a half-written file.
func writeAtomic(path, content string, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	tmp, err := os.CreateTemp(dir, ".valhalla-inject-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	// Clean up on any failure path.
	defer func() {
		if _, err := os.Stat(tmpPath); err == nil {
			_ = os.Remove(tmpPath)
		}
	}()

	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
